name: Hermes
description: Chat formatting plugin for PaperMC.
author: Moros
version: ${pluginVersion}
main: me.moros.hermes.Hermes
depend: [PlaceholderAPI]
api-version: 1.17
permissions:
  hermes.admin:
    description: Grants access to all commands.
    default: op
    children:
      hermes.player: true
      hermes.command.reload: true
      hermes.command.socialspy: true
      hermes.format.obfuscated: true
  hermes.player:
    default: true
    children:
      hermes.command.help: true
      hermes.command.version: true
      hermes.command.msg: true
      hermes.command.reply: true
      hermes.format.rgb: true
      hermes.format.bold: true
      hermes.format.strikethrough: true
      hermes.format.underlined: true
      hermes.format.italic: true
